name: Build
on: [push, pull_request]
jobs:
  ctan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: release.sh
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./release.sh
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build my_cv.pdf
        uses: dante-ev/latex-action@latest
        with:
          root_file: my_cv.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Gather build artifacts
        run: |
          mkdir build
          mv my_csv.pdf build/
          cp -r README.md .github/_config.yml build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
