name: Build
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build my_cv.pdf
        uses: dante-ev/latex-action@latest
        with:
          root_file: my_cv.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: Gather build artifacts
        run: |
          mkdir build
          mv my_cv.pdf build/Jonathan_Schweder_CV.pdf
          cp -r README.md build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
